version: '3.8'

services:
  # ganache:
  #   build: 
  #     context: ./
  #     dockerfile: ./docker/Dockerfile-ganache-ui
  #   tty: true
  #   ports:
  #     - 7545:7545
  #     - 5900:5900
  #   volumes: 
  #     - ./:/home/node/app
  #     - /home/node/app/node_modules

  app:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes: 
      - ./:/home/node/app
      - /home/node/app/node_modules

  remix:
    image: remixproject/remix-ide:latest
    ports:
      - 8080:80
    tty: true
